Zabbix告警：服务器:{HOSTNAME}发生: {TRIGGER.NAME}故障!
ITEMID:{ITEM.ID}
主机:{HOST.NAME}
主机IP:{HOST.IP}
时间:{EVENT.DATE} {EVENT.TIME}
等级:{TRIGGER.SEVERITY}
信息: {TRIGGER.NAME}
项目:{TRIGGER.KEY}
详情:{ITEM.NAME}:{ITEM.VALUE}
状态:{TRIGGER.STATUS}:{ITEM.VALUE}
事件ID:{EVENT.ID}

恢复操作
Zabbix告警：服务器:{HOST.NAME}: {TRIGGER.NAME}问题已恢复!
ITEMID:{ITEM.ID}
主机:{HOST.NAME}
主机:{HOST.IP}
时间:{EVENT.DATE} {EVENT.TIME}
等级:{TRIGGER.SEVERITY}
信息: {TRIGGER.NAME}
项目:{TRIGGER.KEY}
详情:{ITEM.NAME}:{ITEM.VALUE}
状态:{TRIGGER.STATUS}:{ITEM.VALUE}
事件ID:{EVENT.ID}